### PR TITLE
Add Linux and Cygwin installation instructions

### PR DESCRIPTION
**Pull request by XenHat**

### CODE REVIEW

**Review by charles-hollenbeck — COMMENTED** [review]
@XenHat Why use cygwin when Windows already has a ruby installer that you can add the devkit to? http://rubyinstaller.org/

**Comment by XenHat** [comment]
The real reason for this is that the instructions used to be for rails, and it threw errors at me when I started writing the windows version today. I'll investigate native support.

**Comment by charles-hollenbeck** [comment]
Let me know what the errors were with Rails (however this application doesn't use it). I know Rails 5 has a few problems with windows which I've worked out before. As a note though you don't need Rails to use Ruby on windows

**Comment by XenHat** [comment]
Okay

**Pull request closed without merging**
